### ISSUE TITLE
Impossible to import Exceptions

### ISSUE THREAD

**Issue by tom-weiss** [muxinc/mux-python#13] opened 2019-12-03 21:59 UTC
A number of exceptions are thrown by muxpython but none of them can by caught by clients because:

1. They are not exported.
2. the function rest() in `__init__.py` is making it impossible to import them directly from rest.py

The simplest solution would be to export them all in `__init__.py`.

I'm happy to make a pull request if you'd like?

**Comment by mmcc** [comment] 2019-12-03 23:49
Thanks for the report! This SDK is generated from our OpenAPI spec templates, which we haven’t open sourced yet (soon!). We’ll get this fixed there.

**Comment by theRealWardo** [comment] 2019-12-05 17:59
hey @tom-weiss - can you clarify which `__init__.py` you are talking about? I believe `mux_python.rest` should exist and exceptions should be available like `mux_python.rest.NotFoundException`. you also could try `from mux_python import rest as mux_exceptions` and then use `mux_exceptions.NotFoundException`.

also can you please do the following and share your result so we can understand your environment better.
1. start an interactive python in your application's context then
1. `import mux_python`
1. `print(mux_python.__version__)`
1. `'rest' in dir(mux_python)`

here's an example output I am looking for:
```
Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mux_python
>>> print(mux_python.__version__)
1.2.2
>>> 'rest' in dir(mux_python)
True
```

**Comment by GeneticGenesis** [comment] 2020-02-06 19:04
Closing issue as we can't reproduce. Please re-open if you are able to reproduce @tom-weiss

**Closed by GeneticGenesis** 2020-02-06 19:04 UTC
